/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
   This file is automatically generated! */

#include "vmlinux.h"
#include <bpf/bpf_tracing.h>
#include "ktrace.h"

char LICENSE[] SEC("license") = "Dual BSD/GPL";

struct {
	__uint(type, BPF_MAP_TYPE_RINGBUF);
	__uint(max_entries, 167772160);
} rb SEC(".maps");

uint64_t events_lost = 0;

pid_t process_pid0 = 0;

SEC("tp/sched/sched_process_exec")
int handle_exec(struct trace_event_raw_sched_process_exec *ctx)
{

	char comm0[13 + 1];
	bpf_get_current_comm(comm0, 13 + 1);
	if (bpf_strncmp(comm0, 13, "mmap_mprotect" ) == 0) {
		process_pid0 = bpf_get_current_pid_tgid() >> 32;
		bpf_printk("EXEC mmap_mprotect: pid = %d\n", process_pid0);
	}

	return 0;
}

SEC("tp/sched/sched_process_exit")
int handle_exit(struct trace_event_raw_sched_process_template *ctx)
{
    pid_t pid;
    pid = bpf_get_current_pid_tgid() >> 32;

	if (pid == process_pid0) {
		bpf_printk("EXIT mmap_mprotect: pid = %d\n", process_pid0);
		process_pid0 = 0;
	}

	return 0;
}




SEC("kretprobe/__alloc_pages")
int BPF_KRETPROBE(__alloc_pages_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (0 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__alloc_pages")
int BPF_KPROBE(__alloc_pages)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (0 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__cgroup_throttle_swaprate")
int BPF_KRETPROBE(__cgroup_throttle_swaprate_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (1 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__cgroup_throttle_swaprate")
int BPF_KPROBE(__cgroup_throttle_swaprate)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (1 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__clear_user")
int BPF_KRETPROBE(__clear_user_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (2 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__clear_user")
int BPF_KPROBE(__clear_user)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (2 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__cond_resched")
int BPF_KRETPROBE(__cond_resched_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (3 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__cond_resched")
int BPF_KPROBE(__cond_resched)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (3 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__do_fault")
int BPF_KRETPROBE(__do_fault_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (4 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__do_fault")
int BPF_KPROBE(__do_fault)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (4 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__handle_mm_fault")
int BPF_KRETPROBE(__handle_mm_fault_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (5 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__handle_mm_fault")
int BPF_KPROBE(__handle_mm_fault)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (5 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__intel_pmu_enable_all.isra.0")
int BPF_KRETPROBE(__intel_pmu_enable_all_isra_0_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (6 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__intel_pmu_enable_all.isra.0")
int BPF_KPROBE(__intel_pmu_enable_all_isra_0)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (6 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__split_huge_pmd")
int BPF_KRETPROBE(__split_huge_pmd_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (7 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__split_huge_pmd")
int BPF_KPROBE(__split_huge_pmd)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (7 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__split_vma")
int BPF_KRETPROBE(__split_vma_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (8 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__split_vma")
int BPF_KPROBE(__split_vma)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (8 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__x64_sys_execve")
int BPF_KRETPROBE(__x64_sys_execve_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (9 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__x64_sys_execve")
int BPF_KPROBE(__x64_sys_execve)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (9 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/__x64_sys_mprotect")
int BPF_KRETPROBE(__x64_sys_mprotect_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (10 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/__x64_sys_mprotect")
int BPF_KPROBE(__x64_sys_mprotect)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (10 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/acct_collect")
int BPF_KRETPROBE(acct_collect_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (11 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/acct_collect")
int BPF_KPROBE(acct_collect)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (11 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/anon_vma_clone")
int BPF_KRETPROBE(anon_vma_clone_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (12 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/anon_vma_clone")
int BPF_KPROBE(anon_vma_clone)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (12 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/anon_vma_interval_tree_insert")
int BPF_KRETPROBE(anon_vma_interval_tree_insert_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (13 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/anon_vma_interval_tree_insert")
int BPF_KPROBE(anon_vma_interval_tree_insert)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (13 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/anon_vma_interval_tree_remove")
int BPF_KRETPROBE(anon_vma_interval_tree_remove_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (14 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/anon_vma_interval_tree_remove")
int BPF_KPROBE(anon_vma_interval_tree_remove)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (14 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/begin_new_exec")
int BPF_KRETPROBE(begin_new_exec_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (15 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/begin_new_exec")
int BPF_KPROBE(begin_new_exec)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (15 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/bprm_execve")
int BPF_KRETPROBE(bprm_execve_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (16 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/bprm_execve")
int BPF_KPROBE(bprm_execve)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (16 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/change_protection")
int BPF_KRETPROBE(change_protection_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (17 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/change_protection")
int BPF_KPROBE(change_protection)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (17 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/clear_huge_page")
int BPF_KRETPROBE(clear_huge_page_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (18 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/clear_huge_page")
int BPF_KPROBE(clear_huge_page)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (18 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/clear_subpage")
int BPF_KRETPROBE(clear_subpage_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (19 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/clear_subpage")
int BPF_KPROBE(clear_subpage)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (19 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/deferred_split_huge_page")
int BPF_KRETPROBE(deferred_split_huge_page_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (20 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/deferred_split_huge_page")
int BPF_KPROBE(deferred_split_huge_page)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (20 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/do_execveat_common.isra.0")
int BPF_KRETPROBE(do_execveat_common_isra_0_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (21 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/do_execveat_common.isra.0")
int BPF_KPROBE(do_execveat_common_isra_0)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (21 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/do_exit")
int BPF_KRETPROBE(do_exit_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (22 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/do_exit")
int BPF_KPROBE(do_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (22 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/do_group_exit")
int BPF_KRETPROBE(do_group_exit_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (23 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/do_group_exit")
int BPF_KPROBE(do_group_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (23 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/do_huge_pmd_anonymous_page")
int BPF_KRETPROBE(do_huge_pmd_anonymous_page_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (24 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/do_huge_pmd_anonymous_page")
int BPF_KPROBE(do_huge_pmd_anonymous_page)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (24 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/do_mprotect_pkey")
int BPF_KRETPROBE(do_mprotect_pkey_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (25 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/do_mprotect_pkey")
int BPF_KPROBE(do_mprotect_pkey)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (25 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/exit_mmap")
int BPF_KRETPROBE(exit_mmap_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (26 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/exit_mmap")
int BPF_KPROBE(exit_mmap)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (26 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/filemap_fault")
int BPF_KRETPROBE(filemap_fault_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (27 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/filemap_fault")
int BPF_KPROBE(filemap_fault)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (27 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/find_vma")
int BPF_KRETPROBE(find_vma_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (28 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/find_vma")
int BPF_KPROBE(find_vma)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (28 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/finish_task_switch.isra.0")
int BPF_KRETPROBE(finish_task_switch_isra_0_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (29 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/finish_task_switch.isra.0")
int BPF_KPROBE(finish_task_switch_isra_0)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (29 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/flush_tlb_func")
int BPF_KRETPROBE(flush_tlb_func_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (30 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/flush_tlb_func")
int BPF_KPROBE(flush_tlb_func)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (30 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/flush_tlb_mm_range")
int BPF_KRETPROBE(flush_tlb_mm_range_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (31 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/flush_tlb_mm_range")
int BPF_KPROBE(flush_tlb_mm_range)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (31 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/free_swap_cache")
int BPF_KRETPROBE(free_swap_cache_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (32 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/free_swap_cache")
int BPF_KPROBE(free_swap_cache)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (32 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/get_page_from_freelist")
int BPF_KRETPROBE(get_page_from_freelist_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (33 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/get_page_from_freelist")
int BPF_KPROBE(get_page_from_freelist)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (33 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/handle_mm_fault")
int BPF_KRETPROBE(handle_mm_fault_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (34 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/handle_mm_fault")
int BPF_KPROBE(handle_mm_fault)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (34 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/kthread_blkcg")
int BPF_KRETPROBE(kthread_blkcg_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (35 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/kthread_blkcg")
int BPF_KPROBE(kthread_blkcg)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (35 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/load_elf_binary")
int BPF_KRETPROBE(load_elf_binary_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (36 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/load_elf_binary")
int BPF_KPROBE(load_elf_binary)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (36 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/mmput")
int BPF_KRETPROBE(mmput_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (37 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/mmput")
int BPF_KPROBE(mmput)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (37 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/mprotect_fixup")
int BPF_KRETPROBE(mprotect_fixup_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (38 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/mprotect_fixup")
int BPF_KPROBE(mprotect_fixup)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (38 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/native_flush_tlb_one_user")
int BPF_KRETPROBE(native_flush_tlb_one_user_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (39 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/native_flush_tlb_one_user")
int BPF_KPROBE(native_flush_tlb_one_user)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (39 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/p9_client_read")
int BPF_KRETPROBE(p9_client_read_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (40 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/p9_client_read")
int BPF_KPROBE(p9_client_read)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (40 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/p9_client_read_once")
int BPF_KRETPROBE(p9_client_read_once_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (41 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/p9_client_read_once")
int BPF_KPROBE(p9_client_read_once)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (41 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/p9_client_rpc")
int BPF_KRETPROBE(p9_client_rpc_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (42 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/p9_client_rpc")
int BPF_KPROBE(p9_client_rpc)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (42 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/page_cache_ra_unbounded")
int BPF_KRETPROBE(page_cache_ra_unbounded_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (43 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/page_cache_ra_unbounded")
int BPF_KPROBE(page_cache_ra_unbounded)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (43 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/page_remove_rmap")
int BPF_KRETPROBE(page_remove_rmap_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (44 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/page_remove_rmap")
int BPF_KPROBE(page_remove_rmap)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (44 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/prep_compound_page")
int BPF_KRETPROBE(prep_compound_page_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (45 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/prep_compound_page")
int BPF_KPROBE(prep_compound_page)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (45 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/prepare_to_wait_event")
int BPF_KRETPROBE(prepare_to_wait_event_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (46 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/prepare_to_wait_event")
int BPF_KPROBE(prepare_to_wait_event)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (46 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/read_cache_pages")
int BPF_KRETPROBE(read_cache_pages_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (47 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/read_cache_pages")
int BPF_KPROBE(read_cache_pages)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (47 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/read_pages")
int BPF_KRETPROBE(read_pages_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (48 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/read_pages")
int BPF_KPROBE(read_pages)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (48 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/release_pages")
int BPF_KRETPROBE(release_pages_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (49 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/release_pages")
int BPF_KPROBE(release_pages)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (49 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/schedule")
int BPF_KRETPROBE(schedule_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (50 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/schedule")
int BPF_KPROBE(schedule)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (50 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/tlb_flush_mmu")
int BPF_KRETPROBE(tlb_flush_mmu_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (51 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/tlb_flush_mmu")
int BPF_KPROBE(tlb_flush_mmu)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (51 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/unlock_page_memcg")
int BPF_KRETPROBE(unlock_page_memcg_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (52 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/unlock_page_memcg")
int BPF_KPROBE(unlock_page_memcg)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (52 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/unmap_page_range")
int BPF_KRETPROBE(unmap_page_range_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (53 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/unmap_page_range")
int BPF_KPROBE(unmap_page_range)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (53 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/unmap_vmas")
int BPF_KRETPROBE(unmap_vmas_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (54 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/unmap_vmas")
int BPF_KPROBE(unmap_vmas)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (54 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/v9fs_fid_readpage")
int BPF_KRETPROBE(v9fs_fid_readpage_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (55 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/v9fs_fid_readpage")
int BPF_KPROBE(v9fs_fid_readpage)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (55 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kretprobe/v9fs_vfs_readpages")
int BPF_KRETPROBE(v9fs_vfs_readpages_exit)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (56 << 4) | 0x1;
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}

SEC("kprobe/v9fs_vfs_readpages")
int BPF_KPROBE(v9fs_vfs_readpages)
{
	pid_t pid, tid;
	u64 id;
	id = bpf_get_current_pid_tgid();
	pid = id >> 32;
	tid = (u32) id;
    if ((pid != process_pid0 ) || pid == 0) {
		return 0;
	}

	/* reserve sample from BPF ringbuf */
	struct event *e = bpf_ringbuf_reserve(&rb, sizeof(*e), 0);
	if (!e) {
		events_lost++;
		return 0;
	}

	// 32 lowest bits: pid, 32 upper bits: func ID (28b) + event type (4b)
	e->data[0] = (56 << 4);
	// Make it the upper bits
	e->data[0] <<= 32;
	// Add PID
	e->data[0] |= pid;
	e->data[1] = 0; // Clear (for mind's tranquility)
	e->data[1] |= tid;
	e->data[2] = bpf_ktime_get_ns();
	/* successfully submit it to user-space for post-processing */
	bpf_ringbuf_submit(e, 0);
	return 0;
}
