perun_templates_style_dir = perun_templates_dir / 'style'

perun_templates_style_files = files(
    'division_anchor.css',
    'general_setup.css',
    'general_sidebar.css',
    'layout.css',
    'notes_sidebar.css',
    'pins.css',
    'side_panel.css',
    'tag.css'
)

py3.install_sources(
    perun_templates_style_files,
    subdir: perun_templates_style_dir
)