perun_templates_style_dir = perun_templates_dir / 'style'

perun_templates_style_files = files(
    'colors_setup.css',
    'division_anchor.css',
    'environment_sidepanel.css',
    'footer.css',
    'general_setup.css',
    'graph_grids.css',
    'chatbot.css',
    'layout.css',
    'navigation_sidepanel.css',
    'notes.css',
    'pins.css',
    'sankey_graph.css',
    'overview.css',
    'tag.css',
    'themes_sidepanel.css',
    'tooltip.css',
    'trace_details.css',
    'traces_table.css',
    'tree_map.css',
)

py3.install_sources(
    perun_templates_style_files,
    subdir: perun_templates_style_dir
)