"""Flame graph visualization of the profiles."""

from __future__ import annotations

# Standard Imports
import pathlib
from typing import Any

# Third-Party Imports
import click

# Perun Imports
from perun.cli_groups import shared_options
from perun.profiles import native as profile_factory, structs
from perun.profiles.conversions import native_folded
from perun.utils.structs.view_structs import FlameGraphSettings
from perun.view.flamegraph import core


@click.command("flamegraph")
@shared_options.flamegraph_cli_options
@shared_options.profile_postprocess_cli_options
@shared_options.profile_aggregation_cli_option
@click.option(
    "--output-path",
    "-o",
    type=pathlib.Path,
    default=pathlib.Path("./flame.svg"),
    help="Sets the output file path (default=./flame.svg).",
)
@profile_factory.pass_profile
def flamegraph(profile: profile_factory.Profile, output_path: pathlib.Path, **kwargs: Any) -> None:
    """Flame graph interprets the relative and inclusive presence of the
    resources according to the stack depth of the origin of resources.

    \b
      * **Limitations**: `memory` or `time` profiles generated by
        :ref:`collectors-memory` or :ref:`collectors-kperf`.
      * **Interpretation style**: graphical
      * **Visualization backend**: HTML

    Flame graph intends to quickly identify hotspots, that are the source of
    the resource consumption complexity. On X axis, a relative consumption of
    the data is depicted, while on Y axis a stack depth is displayed. The wider
    the bars are on the X axis are, the more the function consumed resources
    relative to others.

    **Acknowledgements**: Big thanks to Brendan Gregg for creating the original
    perl script for creating flame graphs w.r.t folded format: https://brendangregg.com.

    The example output of the flamegraph is more or less as follows::

        \b
                            `
                            -                         .
                            `                         |
                            -              ..         |     .
                            `              ||         |     |
                            -              ||        ||    ||
                            `            |%%|       |--|  |!|
                            -     |## g() ##|     |#g()#|***|
                            ` |&&&& f() &&&&|===== h() =====|
                            +````||````||````||````||````||````

    Refer to :ref:`views-flame-graph` for more thorough description and
    examples of the interpretation technique. Refer to
    :func:`perun.profile.convert.to_flame_graph_format` for more details how
    the profiles are converted to the flame graph format.
    """
    params = structs.PostprocessParameters(**kwargs)
    folded_stream = native_folded.native_to_folded(profile, agg_func=params.agg_func)
    core.generate_flamegraph(
        folded_stream,
        output_path,
        core.generate_title(profile["header"]),
        FlameGraphSettings.from_cli(**kwargs),
        params,
    )
